# Generated by Django 5.1.6 on 2025-03-10 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
